### ISSUE TITLE
indefatigable does remove injuries

### ISSUE THREAD

**Issue by JHallPD** [hypnotoadtrance/MoreTraits#15]
Hey on mp at least indefatigable is removing injuries so people can take injured and broken leg and heal it instantly

**Comment by Xenu47** [comment]
It is working as intended, injuries are cured, description should have been '... does not remove zombification'. This was adressed in https://github.com/hypnotoadtrance/MoreTraits/commit/683f24f1d3b9fe6b8d2af62ec1692ffd5051c048

Next steam workshop release will have it's description fixed.

**Comment by hypnotoadtrance** [comment]
> Hey on mp at least indefatigable is removing injuries so people can take injured and broken leg and heal it instantly

That's kind of a scummy thing for people to do. I suppose I could make it so that Indefatigable must cooldown before it can be used first. But that would require people waiting a whole week before seeing the benefits of it.

There is also the argument to be made that these people are effectively wasting their "Silver Bullet" immediately to cure their wounds when the idea of Indefatigable is to save your ass when you get swamped by zombies and give you a precious moment to escape.

By using this ability immediately, they need to wait another 7 days before it recharges.

So i'm not sure whether that evens it out?

**Comment by JHallPD** [comment]
Sounds good, closing.
