### ISSUE TITLE
The "InfectionLevel" after checking "IsInfected" will still be calculated implicitly.

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [hypnotoadtrance/MoreTraits#23]
Test with Debug mode in SinglePlayer
Simulate being bitten at different times

https://user-images.githubusercontent.com/97338615/148641581-9c9bf685-bb61-4f56-8f7a-9721626827a9.mp4

**Comment by 7UMENGL1aNG** [comment]
>Test with Debug mode in SinglePlayer 
Simulate being bitten at different times
> 
>  Super-Immune.mp4 
> .

**Comment by hypnotoadtrance** [comment]
Excellent documentation.
Issue fixed in: https://github.com/hypnotoadtrance/MoreTraits/commit/d1ff5ccf394a31e6b328d071e35b189f1fd37139

**Comment by 7UMENGL1aNG** [comment]
https://user-images.githubusercon@hypnotoadtrance ent.com/97338615/148644658-084f8c9e-4cc3-4101-b719-c22f7a2296ac.mp4

@hypnotoadtrance Thank you for wanting to try to fix this,but "IsInfected" will still be calculated implicitly.Maybe it can't be changed.

**Comment by hypnotoadtrance** [comment]
If Set Infection Level (0) does not prevent the calculation, then this looks like a Project Zomboid issue. Since these are the tools they provide. That's a right shame.

**Comment by 7UMENGL1aNG** [comment]
Let's try this.

**Comment by 7UMENGL1aNG** [comment]
A proposal(I don't know if it is feasible): 
A chance to cancel the infection after being bitten.
↓
Modify the chance of infection of the attacked person who has "Super-Immune".

**Comment by hypnotoadtrance** [comment]
If this function does not work, I do not know how to alter it. This will remain an open issue.

**Comment by 7UMENGL1aNG** [comment]
I'm sorry I couldn't be of more help.

**Comment by hypnotoadtrance** [comment]
Can try these too, not sure:
setInfectionGrowthRate(0);
setInfectionTime(0);
setInfectionMortalityDuration(0);

**Comment by 7UMENGL1aNG** [comment]
Give me a second

**Comment by Xenu47** [comment]
There is more to it:
If Player was once infected (`getPlayer():getBodyDamage():isInfected()` returned true), InfectionLevel will always grow with time, no matter if Player is stilll Inected or not.

Set myself infected, waited about a day, entered these commands (`->` - their results):
```lua
getPlayer():getBodyDamage():setInfected(false)
print(getPlayer():getBodyDamage():isInfected()) -> false
print(getPlayer():getBodyDamage():getInfectionLevel()) -> 33.89821
print(getPlayer():getBodyDamage():getInfectionLevel()) -> 33.89821
print(getPlayer():getBodyDamage():getInfectionLevel()) -> 33.89821
getPlayer():getBodyDamage():setInfectionLevel(0)
print(getPlayer():getBodyDamage():getInfectionLevel()) -> 0
getPlayer():getBodyDamage():setInfected(true)
print(getPlayer():getBodyDamage():isInfected()) -> true
print(getPlayer():getBodyDamage():getInfectionLevel()) -> 34.29431
```

Also took zombification cure, it's behavior was the same as output of commands mentioned earlier. After Player gets infecred again, his InfectionLevel is increased relative to time passed since infection was disabled.

Base game antibiotics state:
> Fights wound infections. Cannot prevent zombification.

However they do not affect output of `print(getPlayer():getBodyDamage():isInfected())`.

---
Commands:
```lua
getPlayer():setGodMod(true)
getPlayer():setGodMod(false)
```
Partially solve the issue, but I can not find how exactly it does that. 
**Important to note**: it also restores every character stat to full.
